#!/usr/bin/env python3

# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause-Clear

import glob
import json
from pathlib import Path
import stat
import sys

# TODO: make these commandline options
destdir = "./output"
hookfilename = "vendor-hook"
cdifilename = "qualcomm.json"

def find_devicenodes(deviceglob):
    files = glob.glob(deviceglob)
    return files

def generate_devicenodes_cdi(nickname, filesglob):
    if filesglob:
        rendernodeindex = 0
        rendernodelist = [None] * (len(filesglob) + 1)
        for rendernode in sorted(filesglob):
            gpu_path = {"path": rendernode} 
            gpu_pathlist = { "deviceNodes": [ gpu_path ] }
            device_gpu = { "name": nickname+str(rendernodeindex), "containerEdits": gpu_pathlist }
            print(device_gpu, file=sys.stderr)
            rendernodelist[rendernodeindex] = device_gpu
            rendernodeindex += 1

        catchallindex = 0
        gpu_paths = [None] * len(filesglob)
        for rendernode in sorted(filesglob):
            gpu_paths[catchallindex] = {"path": rendernode}
            catchallindex += 1
        gpu_pathlist = { "deviceNodes":  gpu_paths  }
        device_gpus = { "name": nickname+":all", "containerEdits": gpu_pathlist }
        rendernodelist[rendernodeindex] = device_gpus
    else:
        rendernodelist = []
    return rendernodelist

# Find rendernodes and create entries for them
rendernodes = find_devicenodes('/dev/dri/render*')
render_cdi = generate_devicenodes_cdi('render', rendernodes)

# Find all videonoodes and generate entries
# TODO: add input/output filters to make selecting between encoders, decoders and cameras easier
videonodes = find_devicenodes('/dev/video*')
video_cdi = generate_devicenodes_cdi('video', videonodes)

# Check for DMA heap
dmaheaps = find_devicenodes('/dev/dma_heap/*system')
dmaheap_cdi = generate_devicenodes_cdi('dmaheap-system', dmaheaps)

# Check for DSP nodes
cdsps = find_devicenodes('/dev/fastrpc-cdsp*')
cdsps_cdi = generate_devicenodes_cdi('fastrpc-cdsp', cdsps)

# Host-side helpers
# TODO: generate helper scripts based the results of the above probes
hooks = {"hooks" : [ {"hookname": "createContainer", "path": "/bin/" + hookfilename }]}

# Assemble the complete CDI json
cdimain = { "cdiVersion": "0.6.0", "kind": "qualcomm.com/gpu"}
cdimain["devices"] = render_cdi + video_cdi + dmaheap_cdi + cdsps_cdi
cdimain["containerEdits"] = hooks

# Generate hookscript that runs during createContainer
hookscriptbindir = Path(destdir).joinpath('bin')
Path(hookscriptbindir).mkdir(parents=True, exist_ok=True)
hookscriptpath = Path(hookscriptbindir).joinpath(hookfilename)
with open( hookscriptpath, "w") as hookscript:
    hookscript.write("#!/bin/bash\n\n")
    hookscript.write("# This script has been autogenerated by %s\n" % __file__)
    hookscript.write("# Changes made to this file directly *will* be lost\n\n")
    hookscript.write("for node in " + " ".join(videonodes) + " ; do \n\tchmod 0660 ${node}\ndone\n")
hookscript.close()
hookscriptpath.chmod(hookscriptpath.stat().st_mode | stat.S_IEXEC)

# Write out complete CDI json
dynamiccdidir = Path(destdir).joinpath('run/cdi')
Path(dynamiccdidir).mkdir(parents=True, exist_ok=True)
cdipath = Path(dynamiccdidir).joinpath(cdifilename)
with open(cdipath, "w") as cdifile:
    cdifile.write(json.dumps(cdimain))
cdifile.close()
