[metadata]
name = qualcomm-cdi-generator
version = 0.4
description = Qualcomm CDI device generator for container runtimes
long_description = file: README.md
long_description_content_type = text/markdown
license = BSD-3-Clause
url = https://github.com/qualcomm-linux/qualcomm-CDI-generator
python_requires = >=3.8

[options]
py_modules =

[options.data_files]
sbin =
    qualcomm-cdi-generator.py
lib/systemd/system =
    qualcomm-cdi-generator.service
lib/systemd/system-preset =
    10-qualcomm-cdi-generator.preset
lib/udev/rules.d =
    99-qualcomm-cdi-generator.rules
